name: newwhatsapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # UI and Styling
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0

  # Local Parmission
  image_picker: ^1.0.7
  get: ^4.7.2
  flutter_launcher_icons: ^0.14.4
  emoji_picker_flutter: ^4.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'asset/whatsAppLogo.png'
  adaptive_icon_background: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - asset/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
